### ISSUE TITLE
Error when executing get-k8s-info.sh on OpenShift results in error cannot list resource "namespaces" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by gh4nh** [sascommunities/technical-support-code#1]
When execute get-k8s-info.sh there is a call to query namespaces. Namespaces is not a valid resource in OpenShift.

sh-4.4$ ./get-k8s-info.sh --case CS0176345 --namespace genosonar-batch-itu --deploypath /tmp/deploy --out /tmp/get-k8s-info
Error from server (Forbidden): namespaces is forbidden: User "xzy" cannot list resource "namespaces" in API group "" at the cluster scope

ERROR: Error while executing 'oc' commands. Make sure you're able to use 'oc' against the kubernetes cluster before running this script.

Script log saved at: /tmp/get-k8s-info.log
sh-4.4$

**Comment by greg-wootton** [comment]
Namespaces are a valid resource type in OpenShift.

This message: 
`Error from server (Forbidden): namespaces is forbidden: User "xzy" cannot list resource "namespaces" in API group "" at the cluster scope`

indicates you do not have permission to list out the namespaces.

The script runs `oc get namespaces > /dev/null` and if that returns a non-zero return code, the script ends with the second message you see:
`ERROR: Error while executing 'oc' commands. Make sure you're able to use 'oc' against the kubernetes cluster before running this script.`

**Comment by gh4nh** [comment]
Correct my user does not have the permissions to list out the namespace. In many OpenShift deployment projects are used over namespaces. 

sh-4.4$ oc get namespace
Error from server (Forbidden): namespaces is forbidden: User "xyz" cannot list resource "namespaces" in API group "" at the cluster scope
sh-4.4$ oc get project
NAME                       DISPLAY NAME           STATUS
federated-grafana                                 Active
genosonar-batch-etu                               Active
sh-4.4$

@greg-wootton can the script be modified to use projects instead of namespace when running against OpenShift and namespaces is not accessible? The script is not usable for OpenShift deployments where someone who deployes Viya does not have these permissions.

**Comment by greg-wootton** [comment]
The script uses kubectl and oc interchangeably. It tests for the presence of kubectl and if that is not present it tests for the presence of oc, and sets what it finds as the command to use. 

I don't see anywhere in the script where it makes use of the project resource type.

If you'd like to test a possible solution, you could try replacing the get namespaces command with get projects:

For example replacing lines 133-34:
`if ! $KUBECTLCMD get namespaces > /dev/null 2>> $logfile; then
    $KUBECTLCMD get namespaces > /dev/null`
with:
`if ! $KUBECTLCMD get projects > /dev/null 2>> $logfile; then
    $KUBECTLCMD get projects > /dev/null`

and also line 1268:
`    createTask "$KUBECTLCMD get namespaces -o json" "$TEMPDIR/.diagram-tool/namespaces.txt"`
with:
`    createTask "$KUBECTLCMD get projects -o json" "$TEMPDIR/.diagram-tool/namespaces.txt"`

and let us know if that allows the script to complete successfully for you.

**Comment by gh4nh** [comment]
@greg-wootton Those changes worked. Please find attached a version which checks if for OpenShift namespaces are available or otherwise use project.
[get-k8s-info.txt](https://github.com/user-attachments/files/17702234/get-k8s-info.txt)
I can also send this through a merge request.

**Comment by greg-wootton** [comment]
@gh4nh The code has been updated by its author to implement a fix a bit different from what you have proposed, if you'd like to test it.  Details on the changes can be seen here: https://github.com/sascommunities/technical-support-code/commit/be36e48fc677916b2a3fa98de021f68419bb4171
